// auth.js - login/register using localStorage (replace with Firebase Auth if desired)
function getUsers(){ try{return JSON.parse(localStorage.getItem('ep_users')||'[]')}catch(e){return[]} }
function saveUsers(u){ localStorage.setItem('ep_users', JSON.stringify(u)); }
function setCurrent(e){ localStorage.setItem('ep_current', e); }
document.addEventListener('DOMContentLoaded', ()=>{ document.getElementById('btnLogin').addEventListener('click', renderLogin); document.getElementById('btnRegister').addEventListener('click', renderRegister); renderLogin(); });
function renderLogin(){ document.getElementById('authArea').innerHTML = '<h3>Login</h3><input id="li-id" class="input" placeholder="Email ou Telefone"><br><input id="li-pass" class="input" type="password" placeholder="Senha"><br><div style="text-align:center;margin-top:8px"><button id="doLogin" class="btn">Entrar</button></div>'; document.getElementById('doLogin').addEventListener('click', doLogin); }
function renderRegister(){ document.getElementById('authArea').innerHTML = '<h3>Cadastro</h3><input id="re-email" class="input" placeholder="Email"><br><input id="re-phone" class="input" placeholder="Telefone (opcional)"><br><input id="re-name" class="input" placeholder="Nome"><br><input id="re-pass" class="input" type="password" placeholder="Senha"><br><input id="re-age" class="input" type="number" placeholder="Idade"><br><div style="text-align:center;margin-top:8px"><button id="doRegister" class="btn">Criar conta</button></div>'; document.getElementById('doRegister').addEventListener('click', doRegister); }
function doLogin(){ var id = document.getElementById('li-id').value.trim(); var pass = document.getElementById('li-pass').value; var users = getUsers(); var u = users.find(x=> (x.email===id || x.phone===id) && x.password===pass); if(!u){ alert('Identificador ou senha incorretos'); return; } setCurrent(u.email); window.location.href='index.html'; }
function doRegister(){ var email = document.getElementById('re-email').value.trim(); var phone = document.getElementById('re-phone').value.trim(); var name = document.getElementById('re-name').value.trim(); var pass = document.getElementById('re-pass').value; var age = document.getElementById('re-age').value||0; if(!email||!name||!pass){ alert('Preencha email, nome e senha'); return; } var users = getUsers(); if(users.find(x=> x.name.toLowerCase()===name.toLowerCase())){ alert('Nome já existe'); return; } if(users.find(x=> x.email===email)){ alert('Email já cadastrado'); return; } var nu = { email: email, phone: phone, name: name, age: age, password: pass, score: 0, streak: 0, completed: [], friends: [], notifications: [], avatar: null, privateChats: {} }; users.push(nu); saveUsers(users); setCurrent(email); window.location.href='index.html?new=1'; }
